# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

testUser = User.create(name: "test", password: "development", password_confirmation: "development", email: "abc@test.com")

p1 = testUser.posts.create(title: "Why I Would Be Terrified to Be an Israeli", text: "Israel is once again advocating that a Muslim nation is beset on its demise. It must be Wednesday. 
	Thank God, our president, who in his campaign warned us he would change our international image, has bridged the gap between the US and Iran that has not been bridged since the Iranian Hostage conflict in 1979. Now, surely, we can count on Iran to use its nuclear program for good, and begin to join modern civilization…
	And what a fantasy world we could live in. Unfortunately, the new President of Iran, Hassan Rouhani, is what Israeli Prime Minister Benjamin Netanyahu should fear most: charming. So charming, in fact, our president is willing to talk. Before, we did not negotiate with Iran. We heard they were developing their nuclear capabilities so we warned them. When that did not deter, we enacted sanctions. Now, Iran seems to be coming to the negotiating table. And, like a magician gets our attention on one hand while he manipulates us with the other, so Iran has us focused on peaceful talks while they get ever closer to nuclear enrichment.
	The president of Iran said his nation was committed to peace. The true leader of Iran is called the Supreme Leader, Ali Khamenei, who appoints the only two people allowed to run for president. The Supreme Leader is “elected” for life. 
	This true leader of Iran, Ali Khamenei, has been quoted the following on his website in 2010: \"Definitely, the day will come when nations of the region will witness the destruction of the Zionist regime.” And, “How soon or late (Israel's demise) will happen depends on how Islamic countries and Muslim nations approach the issue.\" 
	Iran does not recognize Israel’s right to exit. Their leader clearly wants to Arab world to turn on them. They have been regarded as a rogue state since 1979, and it is common belief they will use nuclear weapons to wipe out Israel as soon as they can. Best of all, Israel’s ally, the US, is not willing to use force to stop it.
	That is why Mr Netanyahu said the following in a speech to the UN General Assembly: “Israel will never acquiesce to nuclear arms in the hands of a rogue regime that repeatedly promises to wipe us off the map. I want there to be no confusion on this point. Israel will not allow Iran to get nuclear weapons. If Israel is forced to stand alone, Israel will stand alone.”
	Why would the prime minister of Israel, a nation any American leader including Mr Obama has sworn to protect, would feel they would need to act alone to prevent a nuclear strike is simply absurd. Israel is very small nation surrounded by nations who publicly deny their right to exist and promise to wipe them off the map. Yet we, the world’s police force involved from Libya to Afghanistan, ignore the issue. 
	Scariest for Netanyahu is the current threat of US government shutdown. With all the politicains playing hot potato on whose head will roll because of the shutdown, no one is listening to the ccalls for support from Israel. What little attention Mr Obama is giving this issue is calling the president of Iran. Many have noted this odd, as he is willing to negotiate with a rogue state but will not negotiate with Republicans.
	In 1948 the Jews of Israel declared independence. The next day, the Arab League declared war on them, and the armies of Egypt, Jordan, Syria, Lebanon, Saudi Arabia, and Iraq invaded Israel. Azzam Pasha, Secretary General of the Arab League, announced that this was a \"Jihad...a war of extermination and a momentous massacre.\" Israel, against all odds, drove the Arabs out. Since then, there have been wars in 1956, 1967, 1973, 1981, and 1982. These wars were  either in defense of their homeland from united Arab threat or invasions of other countries after excessive terrorist attacks. Dozens of smaller conflicts outside of these have also occurred and, recently, Israelis conflicts have occurred when terrorism ravages their borders. They often respond with force. 
	When the Jews were persecuted in Germany, America did not have the resources to get involved, and even when they finally did after Pearl Harbor, we did not really know what was happening in Germany. In 1967, the Six Days war pitted the Arab nations against Israel, with Syria\'s Defense Minister stating that \"the time has come to enter into a battle of annihilation.\" Syria, Egypt and Jordan built their forces up preparing for a strike on Israel. In response, the US declared neutrality, stopped selling arms to Israel, and did nothing to help. If not for Israelis brilliant preemptive strike, they could have been destroyed. America would have been bystanders, having not stepped in when they had the chance. 
	But now we do have a chance. We are more powerful than we were in 1939 and more compassionate than we were in 1967. These are our allies. These are a people with no one else to help. If we do not support them unequivocally, then they are basically on their own against a rogue nation who will soon be nuclear. In 1967, a preemptive strike saved Israel. They will need another one to stop Iran’s nuclear progression. I just pray that America doesn’t find itself watching another Jewish holocaust.")

p2 = testUser.posts.create(title: "Morality and Liberty", text: "In the last fifty years, America has broken away from the moral code of the Bible. Socially conservative parents, to their dismay, watched their children break the molds they thought unbreakable. Today those children have grown to watch their own children defy tradition and history and change the way we, as a society, think about morality. 
This change in thinking is being reflected in a change in governance. These last fifty years have been among the most radical and tradition-shattering times in our history. This raises a complicated question: How do we define morality from a law-making standpoint? With controversial topics like abortion and gay rights, this issue needs to be addressed. My goal in this article is to address these issues with the perspective of a young person who has had openly gay friends and has known girls who have had abortions.
Conflicting perspectives on the separation of church and state significantly influences the idea of right and wrong from a law making-standpoint. This idea of separation, although not in the Constitution, has come to be our definition in determining the legitimacy of a law. Religious people often decry that this “separation” impedes on an American’s right, as stated in the very first Amendment to the Constitution, to freedom of religious expression. 
An illustration of how this is controversial, picture this. A Catholic man is elected to the Senate. A bill comes up that legalizes homosexual unions. He wants to vote against the bill, citing his religious belief in the sanctity of heterosexual unions. What should he do? 
We can propose a solution by defining the way we look at morality. If the federal government dictated that you, an American citizen, no longer have the right to go to church on Sunday, you would be outraged. That would be a clear infringement on your constitutional freedom of religious expression. 
Furthermore, let's say you are a part of a religion that dictates you must kill nonbelievers. Obviously, the federal government forbids this practice, as murder is illegal. However, this is also an infringement on your right to religious expression.
 In the first case, as an American you have the right to attend church. By attending church, you are not infringing on the rights of those around you. In the second case, regardless of your right to religious expression, you do not have the right to practice that part of your murderous religion. Doing so would violate the victim’s right to life, liberty, and the pursuit of happiness. Based on this observation, we can conclude that we have the right to religious expression as long as that expression does not directly infringe on the liberties of others.
This general idea also governs our other laws. With respect to what people are allowed to do when they interact, Americans are mostly left to their own decisions on what is right and what is wrong unless those decisions directly infringe on the rights of others. Whether I believe that my sense of right and wrong comes from God or not, as an American I must accept that others may have a different understanding of morality than I do.
For this reason, right and wrong should not be confused with lawful and unlawful in the context of our American liberty. I believe that it is not moral to cheat on your spouse, but our government does not outlaw this. This is because we do not impose our personal morality on others unless their decisions infringe on the liberty of others. So, a cheating spouse is not breaking the law, even though I am a Catholic and believe such actions are immoral. As an American, the cheater has the liberty to make that decision. 
In current politics, there are two hugely controversial issues that we will apply this rule of morality coupled with liberty. These are abortion and gay rights.
When two men seek to get married, they are making a personal choice they deem moral, a decision that does not infringe on the rights of those around them. As I stated, I am a Catholic. As a Catholic, in order for sex to be moral, two conditions must be met. It must be open to life, and it must be to build love in a marriage. Someone could make the argument that two men love each other, but the fact is, they cannot procreate. The Catholic faith would therefore say homosexual sex is not moral.
But we are not discussing the morality of actions. Rather we are discussing if it should be lawful given our parameters of morality and liberty. For this reason, I oppose gay sexual acts as a Catholic, but as an American, I say gay marriage should be allowed. This is because gay marriage, regardless of personal moral beliefs, does not infringe on the liberty of others. 
As an answer to the question about the Catholic senator posed earlier, he should vote in support of gay marriage. What is lawful should first and foremost be guided by America’s established belief of individual liberty. Our personal understanding of morality cannot govern those around us.
The second issue is abortion. What is fascinating about this discussion is that the murder of a human being is undeniably wrong. So the issue at stake is not murder. Rather, first we must define what a human is. If what is in the mother is a human, then abortion is wrong. That is murder. If what is in the mother is not a human, then abortion becomes about the right of the mother to make personal decisions. 
The comparison must be made between a fetus and an infant. Between the womb and infant life, what has really changed? Like a fetus, an infant cannot protect itself. That responsibility is left to the mother. When a woman raises an infant, she takes on the responsibility of protecting the rights of that human. She is harboring a human life, just like a pregnant woman harbors a human life. 
Humans are different than all other animals because of our conscious thought and ability to make decisions. Infants do not yet have conscious thought and rely on instincts to make decisions. It is not until a later stage in development that a human being develops these abilities. An infant and a fetus are the same because both are developmental stages for a human being. Neither are capable of conscious thought but will be capable eventually, and therefore must be defined as the same being. How can we classify one as human but not the other?
Our individual understanding of personal morality cannot be forced upon this nation of freedom and liberty. The only time government has the responsibility to outlaw an action is when that action takes the personal liberty away from another person. For this reason, gay marriage should be legal, but abortion should not. All laws governing how we interact should be governed by the parameters we have defined.")

p1.comments.create(body: "good post. cant wait to see more!", user_id: testUser.id)





